default['backup']['config']['storage_location'] = '/mnt/backup'
default['backup']['config']['source_location'] = '/var/www/html/upload'
default['backup']['config']['nfs_server_name'] = 'sunfsserver.com'
default['backup']['config']['upload_server_name'] = 'singaporeuniversityuploadsserver.com'
default['backup']['config']['notification_email'] = 'admin@singaporeuniversity.com'
